apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-invoice-production
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-invoice
        env: canary
    spec:
      containers:
      - image: gcr.io/omega-palace-254907/piggy1-invoice:v8
        name: piggyback-prod-runner-invoice
        env:
          - name: JASYPT_ENCRYPTOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jasypt-password
                key: password
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-invoice
          containerPort: 8084
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8084
status: {}
